export const FETCH_PRODUCTS_BEGINN = "FETCH_PRODUCTS_BEGINN"
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"

export const FETCH_METADATA = "FETCH_METADATA"

export const ADD_BOOK_TO_CART_BEGINN = "ADD_BOOK_TO_CART_BEGINN"
export const ADD_BOOK_TO_CART_FAIL = "ADD_BOOK_TO_CART_FAIL"
export const ADD_BOOK_TO_CART_SUCCESS = "ADD_BOOK_TO_CART_SUCCESS"
export const ADD_BOOK_TO_CART = "ADD_BOOK_TO_CART"
export const CLEAR_CART = "CLEAR_CART"
export const REMOVE_EL_FROM_CART = "REMOVE_EL_FROM_CART"