export const FETCH_PRODUCTS_BEGINN = "FETCH_PRODUCTS_BEGINN"
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"

